[package]
name = "tea-arch-chroot-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13.7"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
